version: "3"

services:
  se-hub:
    container_name: 'se-hub'
    image: selenium/hub:3.14.0-europium
    environment:
    - GRID_NEW_SESSION_WAIT_TIMEOUT=1500000
    - GRID_BROWSER_TIMEOUT=1500
    - GRID_TIMEOUT=1500
    networks:
    - br-docker0

  se-node-ch:
    container_name: 'se-node-ch'
    image: selenium/node-chrome-debug:3.14.0-europium
    ports:
    - "5901:5900"
    depends_on:
    - se-hub
    # remove links, see workaround
    # https://github.com/SeleniumHQ/docker-selenium/issues/133
    environment:
    - HUB_PORT_4444_TCP_ADDR=se-hub
    - HUB_PORT_4444_TCP_PORT=4444
    networks:
    - br-docker0
    volumes:
    - ${volume_dir}/se-node-ch/:/var/log/
    - /dev/shm:/dev/shm

  robot:
    container_name: 'robot'
    build:
      context: ${docker_dir}/robot
    stdin_open: true
    tty: true
    depends_on:
    - se-hub
    - se-node-ch
    networks:
    - br-docker0
    volumes:
    - ${docker_dir}/robot:/robot/
    - ${volume_dir}/robot-log/:/var/log/

networks:
  br-docker0:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${br_docker0_ip}${subnet_mask}
    driver_opts:
      com.docker.network.bridge.name: ${br_docker0}
